### ISSUE TITLE
Flashlight flashes after deinstallation

### ISSUE THREAD

**Issue by uli-on** [yahyatinani/flashy-alarm#38]
After deinstalling Flashy Alarm, my flashlight  - activated via tile - now flashes every n seconds. Tried to reinstall, turn the effect off, and deinstall: no effect, even after system reboot. Help!!

**Comment by yahyatinani** [comment]
Hi,
I'm using this app for a very long time now never had such issue. Can you explain step by step how to reproduce this behavior?
Meanwhile, try to install the app again, go to "Flash patterns" page and pick Blink or Signal, tap to customize the  speed, press Test, then press stop.  Go to the app info from Android Settings in your phone, then force stop it.
Hope this solves the issue!

**Comment by yahyatinani** [comment]
@uli-on also please make sure to share if you solved the issue.

**Comment by uli-on** [comment]
Unfortunately, the depicted steps didn't help. And sadly, no, I don't remember exact steps that caused it. I only remember having customised flash speeds in both flashing modes, but don't remember whether I had any setting and/or the listener service activated or not when I deinstalled the app.

Just in case it might ring some bells with you: the light flashes around twice a second.

**Comment by yahyatinani** [comment]
@uli-on That's unfortunate. What is you Android version? 
Try this, activate "Developer options" on your phone and go to "Running services" and see if the app's service is there?
I managed to reproduce almost similar behavior by:
1. Opening the flashlight pattern test vie the app.
2. Going to "Running services" from Developer options and killing the service, but the torch kept flashing.
3. Uninstalling the app turned it off!

If that didn't work. Maybe "Factory reset" from Settings after backing up your data?
If you can provide more info since it's hard to just guess what the bug might be.

**Comment by uli-on** [comment]
Yesss!! That nailed it! Thank you very much!

The only thing I needed to do that you didn't mention was turning on the listener service.

My Android version is a stock v10 coming with Fairphone 3. If you'd like to know further details just ask.

Thanks again!

**Comment by yahyatinani** [comment]
Hi @uli-on, you're welcome and I'm very glad that helped and fixed your phone. And yes I would love to know more details about what exactly nailed it in my solution so I can enhance the app.
Thanks.

**Comment by uli-on** [comment]
The difference was leaving the test running plus stopping the service. 

But meanwhile I had it fixed twice and broken another two times. While Flashy Alarm is not being installed. Currently it's flickering again. Drat!
